### PR TITLE
Add a wooden cup and the mechanism to consume the contained fluid

### PR DESCRIPTION
**Pull request by Josharias**
TODO:
- [ ] Think: Is this really the best spot for this?

### CODE REVIEW

**Comment by xrtariq2594** [comment]
I suppose this is a good place to put it for now. Consuming fluids for restoring hydration levels reminds me of potion drinking in fact.

**Comment by xrtariq2594** [comment]
Actually, after talking with @Cervator , he mentioned that it may be a good idea to move this drinking mechanism over to fluids.

**Comment by Josharias** [comment]
@xrtariq2594, the only problem with that is this mechanism marries the hunger module with the substance module.  Probably not dependencies we want to add to the fluid module. It is a tricky balance between too granular module boundaries, and not granular enough.  

We could create a EdibleSubstances module that does this joining of modules.  Would something like that be better?

**Comment by Josharias** [comment]
Demo video:
https://www.youtube.com/watch?v=tTVu4CE5MHc

**Comment by xrtariq2594** [comment]
Demo video looks good.

I think EdibleSubstances would be better. The Cooking module would benefit from having drinkable containers without having a strict dependency on ManualLabor. After all, we could add things like milk, juice, energy drinks, smoothies, etc.

**Comment by Cervator** [comment]
Just wanted to throw in another option: A "Hydration" module to go with "Hunger" with each of them controlling one bar/system. Hydration could deal with the simple act of a player/creature drinking and becoming more hydrated.

Hunger actually providing both has always kinda _sounded_ weird.

A bridge/combo module could then add more mixed goodies like food items that satisfy both. Like smoothies :-) Cooking, ManualLabor, Fluids, even Anatomy with hydration-specific effects could then base on top of all that as needed.

WoodenCup could go into Hydration with ManualLabor providing a way to craft it while playing JS.

**Comment by xrtariq2594** [comment]
That sounds like a great idea Cerv. I've also found it weird the Hunger manages hydration.

**Comment by Josharias** [comment]
Hrm,  I think it may be useful to keep Hydration separate from SubstanceMatters,  as that may not be in everyone's interest.

So putting this down into a formal plan:
1. New module: Hydration  (possibly Thirst?)
   - Contains extracted logic from Hunger
2. New module: EdibleSubstances
   - Contains this PR's contents

**Comment by Cervator** [comment]
Yeah I don't see Hydration/SubstanceMatters depending on each other, although a bridge module might depend on both.

"Thirst" might work too and fits better with "Hunger" but in theory couldn't "Hydration" also be used to model stuff in plants, soils and such? Technically you could probably still call that thirst, but hmm :-)

Maybe rename Hunger to Sustenance? Then you'd have Hydration and Sustenance instead, with both maybe more applicable to stuff other than the player.

**Comment by Josharias** [comment]
I am hesitant to rename modules.  But I will if I get 2 votes on it.  Would any of you vote on a rename of Hunger to Sustenance?

**Comment by Cervator** [comment]
We're still in Alpha and the Iota series isn't even a thing yet. I'm not too bothered by it, will just need to fix a thing or two :-) So count me in - _IF_ that does seem like a nice name in the first place (more concerned with the final name than the act of renaming)

**Comment by xrtariq2594** [comment]
Sure, count me in as well. Though, we should probably write down a list of modules that depend on hunger.

I know Cooking does for example.

**Comment by Josharias** [comment]
I ended up making "Thirst" because of time constraints.  Feel free to fix the naming.

**Pull request merged**
