### PR TITLE
feat: add particle effect and shearing sound

### PR DESCRIPTION
**Pull request by meetcshah19**

### CODE REVIEW

**Comment by jdrueckert** [comment]
Sound: This is still the old asset, not the new one you posted on discord, is it?
Particles: Waaaaay better! :rocket: I really love the texture, it looks really fluffy :blush: I'm not entirely happy with the particle movement yet, though, mainly because it feels a bit delayed and slow I think :thinking:

**Comment by meetcshah19** [comment]
> Sound: This is still the old asset, not the new one you posted on discord, is it?
> Particles: Waaaaay better! 🚀 I really love the texture, it looks really fluffy 😊 I'm not entirely happy with the particle movement yet, though, mainly because it feels a bit delayed and slow I think 🤔

Right about the sound, fixed it now! For the particle effect, should we increase speed and decrease total duration?

**Comment by jdrueckert** [comment]
> should we increase speed and decrease total duration?

Yes, that's a good idea, let's try that out. Hopefully, I'll also have some time to tinker around a bit with this later today.

**Comment by jdrueckert** [comment]
Didn't find time to figure out why I hear the old asset or the two new ones at once resulting in what sounds like the old one... so this is currently blocked by me, sorry about that.

**Review by jdrueckert — APPROVED** [review]

**Pull request merged**
