### PR TITLE
fix: NUI extraction compability

### PR DESCRIPTION
**Pull request by DarkWeird**

### CODE REVIEW

**Comment by DarkWeird** [comment]
issue: MovingBlocks/Terasology#2307

**Comment by DarkWeird** [comment]
Needs bump up and publish Machines module.
CI build try to build with old Machines module version.

**Comment by DarkWeird** [comment]
issue: MovingBlocks/Terasology#2307

**Review by 4Denthusiast — APPROVED** [review]

**Comment by DarkWeird** [comment]
fixes in https://github.com/Terasology/Machines/pull/38

**Comment by DarkWeird** [comment]
ignore `continuous-integration/jenkins/branch` and `ci/cloudbees/error` jenkins not rewrite this checks on success.

**Pull request merged**
