### PR TITLE
fix: decrease cup volume

### PR DESCRIPTION
**Pull request by APsenpai42**

### CODE REVIEW

**Comment by APsenpai42** [comment]
this PR is linked to- https://github.com/Terasology/EdibleSubstance/pull/6. Both changes effectively increase the amount of thirst replenished by drinking from a vessel.
this is in reference to the issue- https://github.com/Terasology/JoshariasSurvival/issues/66

**Comment by jdrueckert** [comment]
Please elaborate on why you chose the values like you did and how the two PRs work together amgonst themselves and with other drinking and liquid container mechanisms we have.

**Comment by APsenpai42** [comment]
> Please elaborate on why you chose the values like you did and how the two PRs work together amgonst themselves and with other drinking and liquid container mechanisms we have.

@jdrueckert In the issue mentioned, there's a proposal to increase the thirst replenished by drinking from various vessels. The changes made in this pr, and the one linked to it, together make the said changes. Increase hydratingness of water to 1 and decrease cup volume to 50 makes drinking from cup replenish 50% thirst. Volume of waterskin being 500, total thirst replenishing capacity of waterskin becomes 500%,that is, it completely fills up thirst 5 times.

**Review by jdrueckert — APPROVED** [review]
@APsenpai42 Sorry for the delay, GSoC application deadline took it's toll on capacities due to a lot of student proposals to review.

I had a look at your changes in game. Filling more thirst with a cup works fine and everything else seems like it was before :+1:

**Pull request merged**
